use_default_settings: true
server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: !env SECRET_KEY
  
search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json

engines:
  - name: google
    disabled: false
  - name: bing
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: startpage
    disabled: false

outgoing:
  request_timeout: 10.0
  useragent_suffix: ""
  max_request_timeout: 20.0
